name = "newsnow233"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[vars]
G_CLIENT_ID = "Ov23livf2VCrTLephXE5"
G_CLIENT_SECRET = "e49935aaa485ba46bf5c2092b328ff65b9ac4587"
JWT_SECRET = "66666"
INIT_TABLE = "true"
ENABLE_CACHE = "true"

[[d1_databases]]
binding = "DB"
database_name = "newsnows233"
database_id = "7a379cc7-3c0a-49c2-9a06-e7b060c727ed"
