name = "newsnow233"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow233"
database_id = "7a379cc7-3c0a-49c2-9a06-e7b060c727ed"
