name = "newsnow233"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[vars]
G_CLIENT_ID = "Ov23livf2VCrTLephXE5"
G_CLIENT_SECRET = "e49935aaa485ba46bf5c2092b328ff65b9ac4587"
JWT_SECRET = "newsnow233_super_secret_key_1234567890_abcdefg"
INIT_TABLE = "true"
ENABLE_CACHE = "true"

[[d1_databases]]
binding = "DB"
database_name = "new"
database_id = "1e75696c-3d94-4b37-a0ba-f765a62b7aeb"
